/*
 * =====================================================================================
 *
 *       Filename:  VMTranslator.c
 *
 *    Description:  
 *
 *        Version:  1.0
 *        Created:  11/30/23 16:01:21
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Theonessssssss (), whyunotdo@qq.com
 *   Organization:  
 *
 * =====================================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include "CodeWriter.h"

#define EXIT_SUCCESS 0            /*  */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  InitializeRAM
 *  Description:  set sixteen virtual registers, usage described below
 *                  Name    Lacation    Usage
 *                  SP      RAM[0]      stack pointer:the memory address just following
 *                                      the memory address containing the topmost stack
 *                                      value
 *                  LCL     RAM[1]      Base address of the local segment
 *                  ARG     RAM[2]      Base address of the argument segment
 *                  THIS    RAM[3]      Base address of the this segment
 *                  THAT    RAM[4]      Base address of the that segment
 *                  TEMP    RAM[5-12]   Holds the temp segment
 *                  R13                 If the assembly code generated by the VM
 *                  R14     RAM[13-15]  translator needs variables ,it can use these
 *                  R15                 registers. 
 *                Static
 *                  Static variables are mapped on addresses 16 to 255 of the host
 *                  RAM.Each reference to static i in a VM program stored in file
 *                  Foo.vm can be translated to the assembly symbol foo.i.
 *                  the number of static var in a Jack program to 255-16+1=240
 *                Stack
 *                  Stack are mapped on addresses 256 to 2047 of the host RAM
 *                  
 * =====================================================================================
 */
    void
InitializeRAM ( <+argument_list+> )
{
    return <+return_value+>;
}		/* -----  end of function InitializeRAM  ----- */

/* 
 * ===  FUNCTION  ======================================================================
 *         Name:  main
 *  Description:  
 * =====================================================================================
 */
int main ( int argc, char *argv[] )
{
    FILE* file = NULL;
    InputInitializer(file,argv);

    char* currentCommand = NULL;
    while(file){
        if(hasMoreLines(file) != true){
            advance(file, currentCommand);
        }
    }
    return EXIT_SUCCESS;
}				/* ----------  end of function main  ---------- */
